import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'پارادایس | رزور اتاق',
  description: 'Generated by create next app',
};

export default function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Header />

      <main>{children}</main>

      <Footer />
    </div>
  );
}
