import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ThemeProvider from '@/providers/theme-provider';
import { CookiesProvider } from 'next-client-cookies/server';

const yekan = localFont({
  src: [
    { path: '../../public/fonts/Yekan-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../../public/fonts/Yekan-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../../public/fonts/Yekan-Bold.woff2', weight: '700', style: 'normal' },
    { path: '../../public/fonts/Yekan-ExtraBold.woff2', weight: '800', style: 'normal' },
  ],
  variable: '--font-yekan',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'پارادایس | رزور اتاق',
  description: 'Generated by create next app',
};

/*
    ـ
  npm run dev -- -H 192.168.1.105
*/
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='fa' dir='rtl' suppressHydrationWarning className={yekan.variable}>
      <body>
        <CookiesProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
